# Generated by Django 4.1 on 2023-02-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_profile_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_img",
        ),
        migrations.AddField(
            model_name="user",
            name="subtitle",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="user",
            name="video",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
